from setuptools import setup, find_packages

setup(
    name='nativedroid',
    version='1.1',
    url='https://github.com/arguslab/Argus-SAF',
    license='http://www.eclipse.org/legal/epl-v10.html',
    description='Add android analysis support for Angr.',
    packages=find_packages(),
    package_data={
    },
    install_requires=[
        'grpcio==1.9.0',
        'grpcio-tools==1.9.0',
        'claripy==7.8.8.1',
        'cle==7.8.8.1',
        'protobuf==3.6.1',
        'pyvex==7.8.8.1',
        'cffi==1.11.3',
        'bitstring==3.1.6',
        'archinfo==7.8.8.1',
        'pefile==2018.8.8',
        'unicorn==1.0.1',
        'rpyc==4.0.2',
        'plumbum==1.6.6',
        'networkx==2.1',
        'decorator==4.2.1',
        'capstone==3.0.5rc2',
        'cachetools==2.1.0',
        'ailment==7.8.6.16',
        'GitPython==2.1.9',
        'pydot==1.2.4',
        'pyparsing==2.1.4',
        'gitdb==4.0.1',
        'pycparser==2.18',
        'pyelftools==0.25',
        'idalink==0.11',
        'bingraphvis==0.3.0',
        'angr==7.8.8.1',
        'angr-utils==0.4.0'
    ]
)
